name: Scan for Evil Packages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    outputs:
      scan_summary: ${{ steps.scan_echo.outputs.summary }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Clone hof-vulnerabilities-scanner
        run: git clone https://github.com/UKHomeOfficeForms/hof-vulnerabilities-scanner.git
      - name: Run hof-vulnerabilities-scanner
        id: scan_hof_vuln
        run: node hof-vulnerabilities-scanner/index.js
      - name: Save scan-results.json for Slack
        id: scan_echo
        run: |
          if [ -f scan-results.json ]; then
            content=$(jq -c . scan-results.json)
          else
            content="scan-results.json not found"
          fi
          echo "summary=$content" >> $GITHUB_OUTPUT

  notify-slack:
    needs: [ scan ]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SCAN_OUTPUT: ${{ needs.scan.outputs.scan_summary }}
        run: |
          payload=$(jq -n --arg text "$SCAN_OUTPUT" '{text: $text}')
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
